# Generated by Django 3.1.2 on 2020-10-25 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('PostsApp', '0001_initial'), ('PostsApp', '0002_post_author'), ('PostsApp', '0003_auto_20201020_1039'), ('PostsApp', '0004_post_post_ref'), ('PostsApp', '0005_auto_20201021_1020'), ('PostsApp', '0006_auto_20201021_1305')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, db_index=True)),
                ('caption', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('liked', models.ManyToManyField(blank=True, related_name='likers', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='auth.user')),
                ('post_ref', models.CharField(blank=True, db_index=True, default=uuid.uuid4, max_length=100, unique=True)),
            ],
        ),
    ]
